game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('level/<id>',views.show, name = 'show'),
    path('' , views.index , name = 'index'),
    path('formulaire_utilisateur' , views.form_user , name = 'form_user'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

handler404 = 'mysite.views.handler404'

urlpatterns = [
    path('' , views.home , name = 'home'),
    path('contact', views.contact , name = 'contact'),
    path('admin/', admin.site.urls),
    path('game/' , include('game.urls')),
]

game/models.py
from django.db import models

class Level(models.Model):
    name = models.CharField(max_length = 255)
    image = models.CharField(max_length = 255)
    world = models.ForeignKey('World' ,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Player(models.Model):
    login = models.CharField(max_length = 125)
    nb_stars = models.IntegerField()            #min & max
    time = models.IntegerField()
    id_level = models.ForeignKey('Level' ,on_delete=models.CASCADE)
    detail1 = models.BooleanField(default=False)
    detail2 = models.BooleanField(default=False)
    detail3 = models.BooleanField(default=False)
    detail4 = models.BooleanField(default=False)
    detail5 = models.BooleanField(default=False)
    
    def __str__(self):
        return self.login

class Detail(models.Model):
    image = models.CharField(max_length = 255)
    position_x = models.IntegerField()
    position_y = models.IntegerField()
    width = models.IntegerField()
    height = models.IntegerField()
    id_level = models.ForeignKey('Level' ,on_delete=models.CASCADE)

class World(models.Model):
    name = models.CharField(max_length = 255)

    def __str__(self):
        return self.name

game/views.py
from django.shortcuts import render
from .models import Level
from .models import World
from .models import Detail
from .models import Player
from django.http import Http404

def index(request):
    return render(request , 'game/index.html', {'levels' : Level.objects.all()})

def show(request , id):
    try:
        level = Level.objects.get(id=id)
        detail = Detail.objects.filter(id_level = id)
        # mettre les champs details1, details2, details3, details4, details5 à false si tous les champs sont à true + idlevel + 1
        player = Player.objects.get(id=1) 
        print(player.detail1)
    except Level.DoesNotExist:
        raise Http404(id)
    return render(request , 'game/level.html', { 'level' : level, 'detail' : detail})

def form_user(request):
    return render(request , 'game/form_user.html')

mysite/views.py
from django.shortcuts import render


def home(request):
    return render (request , 'pages/home.html')

def contact(request):
    return render (request , 'pages/contact.html')

def handler404(request ,exception):
    return render (request , 'errors/404.html' , {'error' : exception} , status=404)

game/templates/game/form_user.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}Formulaire Utilisateur{% endblock %}

{% block body %}
{% include 'layouts/_nav.html' %}
<body style="background: #0B3C49;">
    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 text-center">
                <img src="{% static 'images/header/header_image.png' %}">
                <h3 style="color: #f3f7fb; font-family: 'Quicksand', sans-serif; margin-bottom: 30%;" >Trouve moi !</h3>
                <form>
                    <div class="form-group">
                        <label for="pseudo" id="lblpseud">Pseudo</label>
                        <input id="pseudo" type="text" class="form-control"  placeholder="Pseudo">
                    </div>
                    <a id="btmpseudo" style="width: 50%;background-color: #f3f7fb; color: #0B3C49;"href="{% url 'game:show' id=1 %}"  class="btn btn btn-lg" role="button" aria-pressed="true">JOUER</a>
                    <!-- <button id="btmpseudo" type="submit" class="btn btn-primary">Submit</button> -->
                </form>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
{% endblock %}

game/templates/game/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}Game{% endblock title %}
<!-- {% block content %} -->
    <!-- <h1>Game page  |  {{levels|length}} Levels</h1>
    {% for level in levels %}
        <article>
            <a href="{% url 'game:show' level.id%}"><h1>{{level.title}}</h1></a>

            <p>{{level.body}}</p>
        </article>
        {% if not forloop.last%}
            <hr>
        {% endif %}
        {% empty %}
            <p>No level available</p>
    {% endfor %} -->
<!-- {% endblock content %} -->

{% block body %}
{% include 'layouts/_nav.html' %}
<body style="background: #0B3C49;">
    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 text-center">
                <img src="{% static 'images/header/header_image.png' %}">
                <h3 style="color: #f3f7fb; font-family: 'Quicksand', sans-serif; margin-bottom: 30%;" >Trouve moi !</h3>
                <a style="width: 50%;" href="{% url 'game:form_user' %}" id="btmjouer" class="btn btn btn-lg" role="button" aria-pressed="true">JOUER</a></br></br>
                <a style="width: 50%;"href="#" id="btmcontinuer" class="btn btn btn-lg" role="button" aria-pressed="true">CONTINUER</a>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
{% endblock %}

game/templates/game/level.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block script %}
    <script type="text/javascript">
        var a = "{{level.name}}";
    </script>
    <script src="{% static 'javascript/script.js' %}"></script>
{% endblock %}

{% block title %}Level {{level.id}}{% endblock title %}

{% block nav %}{% endblock %}
{% block content %}





    <div class="container" id="game_container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card">
                    <div id="nav" class="card-header" >
                            <h3 id="nombre" >0</h3>
                            <i id="etoile" class="fas fa-star" ></i>
                            <i id="question"class="far fa-question-circle" onclick="OpenNoCluePopUp()"></i>
                            <i id="indice" onclick="openPopUpClue()"  class="fas fa-lightbulb"></i>


                        <div class="card" style="background-color:#0B3C49; width: 67%;">
                            <h6  class="text-center" id="texte">{{level.world.name}}</h6>
                        </div>
                    </div>
                    <div class="card-body" >
                        <h5 class="card-title text-center">{{level.name}}</h5>

                        <div class="imagecontainer" style="position: relative;">
                            <img id="painting" src="{% static 'images/' %}{{level.image}}" width="100%" onclick="check('detimg',event)">
                        </div>
                        <div style="display: none; background-color:#f3f7fb; border-radius: 3px; position: absolute; top: 180px; left: 29px; right: 32px; padding: 5px;" class="text-center">
                            <h1 style="color: #0B3C49; ">GAGNE !</h1>
                            <a id="btmsuivant" style="width: 80%;background-color: #0B3C49; color: #f3f7fb ; padding:5px;"href="{{level.id}}"  class="btn btn btn-lg" role="button" aria-pressed="true" >NIVEAU SUIVANT</a>
                        </div>
                    </div>
                    <div class="card-footer text-center">
                        {% for d in detail %}
                            <div id="carde" ><img id="detimg" src="{% static 'images/' %}{{d.image}}" ></div>
                        {% endfor %}
                        <br>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
        <!-- indice à mettre ailleurs -->
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div id="popup">
                    <div class="card-body text-center " >
                      <i id="close"class="far fa-window-close" onclick="closePopUpClue()"></i>
                      <p class=" text-center">Choisir le détail</p>
                      <!--For d in notFoundDetails-->
                      {% for d in detail %}
                          <div id="carde" ><img id="detimg" src="{% static 'images/' %}{{d.image}}" onclick="OpenClueText()"></div>
                      {% endfor %}
                      <!--div id="clueText"> Tu n'as pas besoin d'aide. <br> Ouvre bien tes yeux.</div-->

                      <div class="row " id="clueText">
                          <i id="close"class="far fa-window-close" onclick="CloseClueText()"></i>
                          <div >Tu n'as pas besoin d'aide. <br> Ouvre bien tes yeux.</div>
                      </div>
                    </div>
                </div>
             </div>
       </div>
       <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card-body text-center " id="noClueAvalaible" >
                    <i id="question"class="far fa-window-close" onclick="CloseNoCluePopUp()"></i>
                      Oups tu n'as pas assez d'étoiles
                </div>
            </div>
        </div>
  </div>
{% endblock content %}

mysite/templates/layouts/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark" id="nabvarr">
    <a class="navbar-brand" href="#">Bacchanight</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
            <a href="{% url 'home' %}"><li>Home</li></a>
        </li>
        <li class="nav-item">
            <a href="{% url 'game:index' %}"><li>Game</li></a>
        </li>
        <li class="nav-item">
            <a href="{% url 'contact' %}"><li>Contact</li></a>
        </li>
      </ul>
    </div>
</nav>

mysite/templates/layouts/_nav_level.html
<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <nav class="navbar navbar-expand-lg navbar-dark" id="nabvarr">
                <a class="navbar-brand" href="#">Bacchanight</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                  <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a href="{% url 'home' %}"><li>Home</li></a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'game:index' %}"><li>Game</li></a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'contact' %}"><li>Contact</li></a>
                    </li>
                  </ul>
                </div>
            </nav>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

mysite/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head%}{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
    <link href="https://fonts.googleapis.com/css?family=Acme&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://kit.fontawesome.com/450abf6818.js" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %} | Bacchanight</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block script %} {% endblock %}
</head>
{% block body%}
<body>
    {% block nav %}
    {% include 'layouts/_nav.html' %}
    {% endblock %}
    {% block content %} {% endblock %}
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
{% endblock body%}
</html>

mysite/templates/pages/contact.html
{% extends 'layouts/base.html' %}

{% block title %}Contact{% endblock title %}

{% block content %}
    <h1>Contact page</h1>
{% endblock content %}

mysite/templates/pages/home.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}Home{% endblock%}

{% block body %}
    {% include 'layouts/_nav.html' %}
    <body style="background: #0B3C49;">
    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 text-center">
                <h1 style="color: #f3f7fb; font-family: 'Quicksand', sans-serif; margin-bottom: 30%;">Bacchanight 2020</h1>
                <img style="margin-top : 0%" src="{% static 'images/header/header_image.png' %}">
                <h3 style="color: #f3f7fb; font-family: 'Quicksand', sans-serif; margin-bottom: 30%;" >Trouve moi !</h3>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
{% endblock %}